### ISSUE TITLE
how to use render on gatobot

### ISSUE THREAD

**Issue by C0LoRzz** [CattoDev/GatoBot#3]
it keeps saying ffmpeg is missing even when i have it in the gd directory, or am i putting it in the wrong place

**Comment by tungstengmd** [comment]
has this been fixed?

**Comment by C0LoRzz** [comment]
alr i figured it out, 
u just need to add the bin folder in the ffmpeg folder to system variables

**Comment by tungstengmd** [comment]
no
you just put the exe in the gd dir

**Comment by C0LoRzz** [comment]
> no you just put the exe in the gd dir

that doesn't work for me
